drop table if exists course CASCADE;
drop table if exists group_table CASCADE;
drop table if exists person CASCADE;
create table course (
                        id bigint generated by default as identity,
                        grade varchar(255),
                        language varchar(255),
                        primary key (id)
);
create table group_table (
                             id bigint generated by default as identity,
                             course_id bigint,
                             person_id bigint,
                             primary key (id)
);
create table person (
                        id bigint generated by default as identity,
                        age integer not null,
                        email varchar(255),
                        name varchar(255),
                        primary key (id)
);
alter table group_table
    add constraint FK3iyhyrcwhxlofyax4fpfraj94
        foreign key (course_id)
            references course;
alter table group_table
    add constraint FK9wurj1jhp98jlh9r87nct4f1c
        foreign key (person_id)
            references person;
